[package]
name = "meshvault"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "meshvault"
path = "backend/main.rs"

[dependencies]
axum = "0.7.7"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
stl-thumb = "0.5.0"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
